### ISSUE TITLE
evaluation of Hydra + LDF

### ISSUE THREAD

**Issue by elf-pavlik** [linkeddata/SoLiD#1]
How do you see Hydra and Linked Data Fragments fitting SoLiD? http://www.hydra-cg.com/
I find it especially interesting if LDP can implement similar pattern as intended in hydra:Collection https://www.w3.org/community/hydra/wiki/Collection_Design

**Comment by deiu** [comment]
Unfortunately, there are currently no plans to implement Hydra, nor LD Fragments.
