### ISSUE TITLE
Social WG oriented version of this draft

### ISSUE THREAD

**Issue by elf-pavlik** [linkeddata/SoLiD#18]
I have impression that current version will receive big push back from many Social WG participants. Few suggestions:

1) JSON-LD only, those who want to do Turtle can still do that but now it can scary people away
2) No SPARQL! If it can't function without it than very unlikely people in context of this WG will adopt it, if it can see comment on 1
3) No LDPatch. To get started we can work with PUT and see if [JSON Patch](http://jsonpatch.com/) can satisfy WG use cases. While we seem to agree on not breaking compatibility with RDF as much as we can, I don't think people will agree on RDF first approach.

To clarify, I don't criticize current design, on contrary find it an amazing work. But what for people used to RDF may look like cool way of doing things, very likely will scary away many of Social WG members who at least currently don't look at The Web from this perspective.

**Comment by akuckartz** [comment]
I agree with 1. and 2. Not sure about 3.

**Comment by deiu** [comment]
1) JSON-LD is already supported, so you can ignore Turtle
2) SoLiD doesn't force you to use SPARQL. Just going with regular LDP (RESTful) requests should be enough.
3) Patching is still open for discussion. We could use any of LD Patch, JSON Patch or SPARQL updates.

**Comment by elf-pavlik** [comment]
@deiu I didn't mean that you should change defualt SoLiD draft but creating Social WG oriented **fork** of it can help other WG members to understand it. Of course I no one has cycles to do that I can always try to create such fork myself. I really think that even *not required* Turtle and SPARQL will scary away many Social WG participants

**Comment by evanp** [comment]
I'm confused by this. I thought the whole point of SoLiD (= Social Linked Data) was to apply the Linked Data Platform to the user stories of the Social API. I thought the name was created at the last F2F, even. What else is it used for?

**Comment by sandhawke** [comment]
+1 @evanp

**Comment by deiu** [comment]
What makes it social is the way it handles data sharing. For instance, anyone can build a dedicated Web service that connects to a database, but how would it allow users to share data with anyone on the Web in a decentralized way? To us, "social" means being able to connect people's data.
