### ISSUE TITLE
ACL guidelines

### ISSUE THREAD

**Issue by elf-pavlik** [linkeddata/SoLiD#24]
Little more guidance on ACL would help with understanding it and people deploying solid making sure not to compromise access to information on the server.

1) I understand that ACL works per instance of ldp:Resource (ldp:Container) and one should not allow queries on the whole dataset. 

2) Can one add ldp:member (ldp:contains) triple to include data accessible via certain instance of ldp:Resource in responses of queries made on ldp:Container (used as subject of ldp:member)

3) how setting access on ldp:Container compares to OAuth scopes? https://tools.ietf.org/html/rfc6749#section-3.3 @aaronpk

**Comment by deiu** [comment]
Fixed 1) in 2a6eda14c4a0030479e4304894203c2e96980833.

Not sure what you mean by 2).

3) It doesn't really compare.

**Comment by elf-pavlik** [comment]
Conversation about using Bearer token and app permissions with OAuth scopes started in https://github.com/w3c-social/Social-APIs-Brainstorming/issues/8

I will soon add examples there which show distinction between OAuth based app authorization (permissions) with scopes. User specific access control with Web Access Control. As well as authentication with WebID-*, IndieAuth, OpenID Connect, Persona, Identity Credentials, whatever, independent from former two - app permissions and user access control.

To my understanding, currently SoLiD apps have full / unlimited access to the workspace which person authenticated in using those apps. Control over permissions granted to specific app seems very important and relevant to https://github.com/w3c-social/Social-APIs-Brainstorming/issues/9
