### ISSUE TITLE
"meccano" link in README is broken

### ISSUE THREAD

**Issue by akuckartz** [linkeddata/SoLiD#25]
Access attempts now result in a 404 http error.

**Comment by deiu** [comment]
The link is good, but it points to a protected repository. There isn't much I can do about it, sorry.

**Comment by akuckartz** [comment]
For the record. This issue was/is about this URL:
https://github.com/Qatar-Computing-Research-Institute/qcri-crosscloudP/tree/meccano

**Comment by deiu** [comment]
Yes, it seems github doesn't really understand how ACLs should be implemented. In this case, it shows a 404, even though the resource exists but you're not allowed to see it. It should be a 403.

**Comment by Papipo** [comment]
This might be for privacy reasons though.
