### ISSUE TITLE
WebDAV methods?

### ISSUE THREAD

**Issue by bblfish** [linkeddata/SoLiD#3]
Just saw that there are a lot of METHODS in the SoLiD examples https://github.com/linkeddata/SoLiD

```http
HTTP/1.1 200 OK
Accept-Patch: application/json, application/sparql-update
Accept-Post: text/turtle, application/ld+json
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, PATCH, POST, PUT, MKCOL, DELETE, COPY, MOVE, LOCK, UNLOCK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: User, Triples, Location, Link, Vary, Last-Modified, Content-Length
Allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, MKCOL, DELETE, COPY, MOVE, LOCK, UNLOCK
```

Are all the WebDAV ones used?

**Comment by deiu** [comment]
Yes, they are all supported.

**Comment by bblfish** [comment]
Mhh, that still leaves some open questions, such as how do they work if you are not using WebDAV.

**Comment by bblfish** [comment]
Should I open a new issue for the follow up question? Or can you open it again?

**Comment by bblfish** [comment]
Hi @deiu you should check out the thread on the IETF where we are discussing SEARCH and QUERY with Roy Fielding. https://lists.w3.org/Archives/Public/ietf-http-wg/2015AprJun/0248.html 
You'll see that just one new verb brings up a lot of issues. 

So since we don't need all of WebDAV ( though I find it interesting ) and since WebDAV does raise the bar for implementations very high, I really don't think its a good idea to add it to SoLiD at this point. It's something to tinker and play with, and find inspiration from, but if it looks like its too complex to implement, we'll loose a lot of people.

**Comment by deiu** [comment]
Removed them in c1c34e171e0f1f0afdd676154c79371223e2c9d6
