### ISSUE TITLE
implementation levels

### ISSUE THREAD

**Issue by bblfish** [linkeddata/SoLiD#6]
Different parts of the SoLiD described here have different levels of implementation. Some are well established and even standard like LDP, some are not standardised yet, but have years of experience such as WebID-TLS and Web Access Control.  Some are exploratory but pretty obvious such as the SEARCH method applied to SPARQL Queries. And some are very bleeding edge such as WebID-RSA that requires recent browsers, the development of a protocol for finding stored private keys, and need a security review. (see issue #5 ).

It would be good if the document could make clear for each part 
* which are implemented by which servers or client libraries
* which specs they refer to for their implementation
* ... ?

One could make a simple table for this so as to help guide people about where consensus has been achieved and where more research or implementation feedback is needed.

**Comment by bblfish** [comment]
For example [rww-play](https://github.com/read-write-web/rww-play) implements the following parts of SoLiD:
* LDP Basic Containers
* WebID
* WebAccessControl
* SEARCH ( see issue #4  )
* files are saved on the file system

**Comment by deiu** [comment]
Added in 475898ddb336e127a7d5a4998ed457c866a7583e
