### ISSUE TITLE
rww-play as implementation of SoLiD

### ISSUE THREAD

**Issue by bblfish** [linkeddata/SoLiD#7]
I think [rww-play](https://github.com/read-write-web/rww-play) counts as an implementation of SoLiD. Could that be listed too? This is where a table of features implemented by SoLiD would be useful, and each server can specify which features it implements - perhaps to what level .

**Comment by deiu** [comment]
Yes, can you please create a PR with a new (markdown) file containing all the bullet points you had in https://github.com/linkeddata/SoLiD/issues/6#issuecomment-96326833?
